### ISSUE TITLE
Brazilian-Institute-of-Robotics/robots-flat_fish.git does not exist

### ISSUE THREAD

**Issue by brean** [Brazilian-Institute-of-Robotics/bir.flat_fish-package_set#16]
The repository "robots-flat_fish" does not exist, also it is listed in the source.yml:

    - robots/flat_fish:
        type: git
        url: 'git@github.com:Brazilian-Institute-of-Robotics/robots-flat_fish.git'

**Comment by Thomio-Watanabe** [comment]
This repository is private.
To use the package_set, you will have to delete all references to robots/flat_fish.

**Comment by brean** [comment]
ok, thank you

**Comment by doudou** [comment]
Not right. You can use the package set just fine, you should only not select the package itself.

This can be done by either selecting packages manually (instead of adding bir.flat_fish in your layout), or by adding the following line to autoproj/init.rb:

~~~
metapackage('bir.flat_fish').weak_dependencies = true
~~~

and make sure you have the following to autoproj/manifest:

~~~
layout:
 - bir.flat_fish
exclude_packages:
 - robots/flat_fish
~~~

(Without the weak_dependencies flag, excluding the package would create an error)
